language: python
python:
- '2.7'
matrix:
  fast_finish: true
before_install:
- openssl aes-256-cbc -K $encrypted_269842d0bccb_key -iv $encrypted_269842d0bccb_iv -in vault_password.enc -out vault_password -d
install:
- pip install -U pip
- pip install -U setuptools
- pip install -r packaging/requirements.txt
- pip install -r packaging/requirements-test.txt
script:
- ansible-playbook site.yml --syntax-check
- ansible-playbook site.yml --check
notifications:
  email: false
