---
  - hosts: localhost
    connection: local
    tasks:
      - name: create ssh private key file
        copy:
          content: "{{ ssh_keys.private }}"
          dest: ".id_rsa"
          mode: 0600
        no_log: true
      - name: add ssh key to digital ocean account
        digital_ocean:
          command: ssh
          name: maddison_family_key
          state: present
          api_token: "{{ api_tokens.digital_ocean }}"
          ssh_pub_key: "{{ ssh_keys.public }}"
        register: digital_ocean_ssh_key
  - hosts: all
    tasks:
      - name: set ssh key id
        set_fact:
          digital_ocean_ssh_key_id: "{{ hostvars['localhost'].digital_ocean_ssh_key.ssh_key.id }}"
        when: not ansible_check_mode
      - name: create virtual machine
        delegate_to: localhost
        digital_ocean:
          command: droplet
          name: "{{ inventory_hostname }}"
          state: present
          api_token: "{{ api_tokens.digital_ocean }}"
          unique_name: true
          ipv6: true
          ssh_key_ids: "{{ digital_ocean_ssh_key_id | default(none) }}"
          region_id: "{{ digital_ocean_region }}"
          image_id: "{{ digital_ocean_image }}"
          size_id: "{{ digital_ocean_size }}"
        register: digital_ocean_droplet
      - debug:
          var: digital_ocean_droplet
...
